DROP TABLE IF EXISTS bioimg;

CREATE TABLE bioimg (
    id SERIAL PRIMARY KEY,
    bioimg_id INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    url VARCHAR(300) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
